#ifndef STDIO_TYPES_H
#define STDIO_TYPES_H

#include <stdint.h>

#define NULL (void *)0
#define EOF -1

#define L_tmpnam
#define TMP_MAX

#define SEEK_CUR 0
#define SEEK_END 1
#define SEEK_SET 2

#define NO_IO_OP 0
#define INPUT_OP 1
#define OUTPUT_OP 2

typedef uint64_t size_t;
typedef uint64_t fpos_t;

typedef struct
{
    // File descriptor returned by open syscall.
    int fd;

    // Flags passed to open syscall, generated by mode argument of fopen.
    int flags;

    int last_op;

    // Mode for file buffering. A stream can use full buffering, line buffering or no buffering at all.
    int buff_mode;

    // This is the buffer used by input/output operations
    char *buffer;
    size_t buff_size;

    // Current position in the buffer.
    int buff_pos;

    // Number of characters written to the buffer
    int buff_end;

    // If true, buffer has been allocated by the library, so we need to free it when closing the file, or when changing the current buffer.
    int self_allocated_buff;

} FILE;

#endif
